[build]
  publish = "client/dist"
  command = "cd client && npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Form handling
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = false

# Handle form submissions
[[redirects]]
  from = "/nvgo-order"
  to = "/.netlify/functions/submitOrder"
  status = 200
  conditions = {Role = ["form-submission"]}

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200